import type { NextPage } from "next";
import Head from "next/head";
import tw from "tw-tailwind";

const tw2 = tw`absolute`;
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper1>{tw2}</Wrapper1>
      <Wrapper2 hasBorder>{tw2}</Wrapper2>
      <Wrapper3>{tw2}</Wrapper3>
      <Wrapper4 hasBorder>{tw2}</Wrapper4>
    </div>
  );
};

export default Home;

const Wrapper1 = tw.div`bg-red-500`;
const Wrapper2 = tw.div<{ hasBorder: boolean }>`bg-red-500 ${({ hasBorder }) =>
  hasBorder ? "border-red-500" : ""}`;
const Wrapper3 = tw.div(() => ["bg-red-500"]);
const Wrapper4 = tw.div<{ hasBorder: boolean }>(({ hasBorder }) => [
  "bg-red-500",
  hasBorder && "border-red-500",
]);
