import { Button } from 'components/form/button'
import { IconButton } from 'components/form/iconButton'
import { Input } from 'components/form/input'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef } from 'react'
import tw from 'tw-tailwind'

const Home: NextPage = () => {
  const refExample1 = useRef<HTMLDivElement>(null)
  const refExample2 = useRef<HTMLDivElement>(null)
  const refExample3 = useRef<HTMLDivElement>(null)
  const refExample4 = useRef<HTMLDivElement>(null)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Click me</Button>
      <IconButton>Icon</IconButton>
      <Input />
      <Example1 ref={refExample1} className="p-4">
        Basic template
      </Example1>
      <Example2 ref={refExample2} hasBorder className="p-4">
        Basic template with props
      </Example2>
      <Example3 ref={refExample3} className="p-4">
        Basic function
      </Example3>
      <Example4 ref={refExample4} hasBorder className="p-4">
        Basic function with props
      </Example4>
      <Example5 className="p-4">Test</Example5>
      <Example6 hasBorder className="p-4">
        Test
      </Example6>
      <Example7 className="p-4">Test</Example7>
      <Example8 hasBorder className="p-4">
        Test
      </Example8>
    </div>
  )
}

export default Home

const Example1 = tw.div`bg-red-500`
const Example2 = tw.div<{ hasBorder: boolean }>`bg-red-500 ${({ hasBorder }) => (hasBorder ? 'border-red-500' : '')}`
const Example3 = tw.div(() => ['bg-red-500'])
const Example4 = tw.div<{ hasBorder: boolean }>(({ hasBorder }) => ['bg-red-500', hasBorder && 'border-red-500'])
const Example5 = tw(Button)`bg-red-500 py-28`
const Example6 = tw(Button)<{ hasBorder: boolean }>`bg-red-500 ${({ hasBorder }) => (hasBorder ? 'border-red-500' : '')}`
const Example7 = tw(Button)(() => ['bg-red-500'])
const Example8 = tw(Button)<{ hasBorder: boolean }>(({ hasBorder }) => ['bg-red-500', hasBorder && 'border-red-500'])
// const Example6 = tw(Input)<{ hasBorder: boolean }>``

