import { Button } from 'components/form/button'
import { IconButton } from 'components/form/iconButton'
import { Input } from 'components/form/input'
import type { NextPage } from 'next'
import Head from 'next/head'
import tw from 'tw-tailwind'
import clsx from 'clsx'

const borderColors = { red: tw`border-red-500`, blue: tw`border-blue-500`, green: tw`border-green-500` }
const sharedClasses = tw`border-red-500`

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Button>Click me</Button>
    <IconButton>Icon</IconButton>
    <Input />
    <Example1>Basic template</Example1>
    <Example2 $hasBorder>Basic template with props</Example2>
    <Example3>Basic function</Example3>
    <Example4 $hasBorder>Basic function with props</Example4>
    <Example5>Component template</Example5>
    <Example6 $hasBorder>Component template with props</Example6>
    <Example7>Component function</Example7>
    <Example8 $hasBorder className="p-4" $borderColor="green">
      Component function with props
    </Example8>
    <Example9 className={clsx(borderColors['red'])}>Component function with props</Example9>

    <Example10 label="Components with ref" />
    <div className={sharedClasses}>sharedClasses</div>
  </div>
)

export default Home

const Example1 = tw.div`p-4 bg-red-500`

const Example2 = tw.div<{ $hasBorder: boolean }>`bg-red-500 ${({ $hasBorder }) => ($hasBorder ? 'border-2 border-blue-500' : '')}`

const Example3 = tw.div(() => ['bg-red-500'])

const Example4 = tw.div<{ $hasBorder: boolean }>(({ $hasBorder }) => ['bg-red-500', $hasBorder && 'border-2 border-blue-500'])

const Example5 = tw(Button)`bg-red-500`

const Example6 = tw(Button)<{ $hasBorder: boolean }>`bg-red-500 ${({ $hasBorder }) => $hasBorder && 'border-2 border-blue-500'}`

const Example7 = tw(Button)(() => ['bg-red-500'])

const Example8 = tw(Button)<{ $hasBorder: boolean; $borderColor: keyof typeof borderColors }>(({ $hasBorder, $borderColor }) => [
  '!bg-red-500',
  $hasBorder && ['border-2', borderColors[$borderColor]],
])

const Example9 = tw(Button)`p-4 bg-red-500`

const Example10 = tw(Input)`p-4 bg-red-500`
